{
    "name":"Latihan Addon Management Odoo",
    "version":"1.0",
    "depends":["base","hr",],
    "author":"yusup",
    "category":"Education",
    "website":"https://github.com/yusupnurkarimah",
    "description":"Ini adalah addons management latihan",
    "data":[
        "menu.xml",
        "assetdc.xml",
        "assetnondc.xml",
        "layout.xml",
        "power.xml",
        "lan.xml",
        "sop.xml",
        "bcp.xml",
        "berita.xml",
        "agenda.xml",
        "maintenance.xml",
        "perangkat.xml",
        "sdm.xml",
        "capacity.xml",
        "datauser.xml",
        "datalokasi.xml",
        "dataruang.xml",
        "subruang.xml",
        "merek.xml",
        "unit.xml",
        "subunit.xml",
        "kode.xml",
        "kelompok.xml",
        "security/ir.model.access.csv",
    ],
    
}